### PR TITLE
Feature/progress bar

### PR DESCRIPTION
**Pull request by jeanlouisgicquel**
## Add Progress Bar component

- [x] progress bar grows with v-model

## Question

@alfonsobries A interesting feature/prop with the progress bar could be indeterminate state. To show this state, we could use css animations but tailwind doesn't provide utilities to do that... 
I'm beginner with tailwind but I think it's possible to use plugins to accomplish what we need.
Did you think about a solution ? Let's discuss about it !

### CODE REVIEW

**Comment by alfonsobries** [comment]
@jeanlouisgicquel yeah, I still not aware how the plugins works but sound like the right answer to the problem, Personally, for example, I want to add some kind of busy status to the inputs and that can only be achieved with custom CSS,

I think that for now we should leave the components free or custom CSS and maybe add an example of how the user can achieve that in the docs (like I do for the checkbox https://vue-tailwind.com/elements/checkbox.html#custom-styles)

Im guessing that once we have all the most common components we can focus on think in the best way to add that status as an optional plugin maybe?

**Comment by jeanlouisgicquel** [comment]
OK I agree with you !

**Comment by afflexux** [comment]
Custom utility classes can be added straight into the tailwind.config.js under plugins and they will be generated at build time with the rest of tailwind. They can then be used in the components like any other default tw classes no problem.

```
// tailwind.config.js
module.exports = {
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.skew-10deg': {
          transform: 'skewY(-10deg)',
        },
        '.skew-15deg': {
          transform: 'skewY(-15deg)',
        },
      }

      addUtilities(newUtilities)
    }
  ]
}
```
Goes into more detail here : [Tailwind Docs](https://tailwindcss.com/docs/plugins/#app)

I've been using tailwind for a while now, let me know if I can help at all.

**Comment by alfonsobries** [comment]
Just test the components and I like it but I think is not ready to merge yet.
 
+ I would add status colours, and set the default colour to the blue that we are using as default
+ Some more tests
+ An optional slot for the inner text maybe like to show the progress
 
Hope to make some time to help with that soon, I'm trying to finish a rich select component but I been kind of busy and that is a little complicated

**Comment by doot0** [comment]
Tailwind now provides animation utils. Does this have any implications for this component?

**Comment by alfonsobries** [comment]
@doot0 yeah sounds like we can use that for a progress bar/icon component, ill work in one for the current version (1.0) once I finish the datepicker,

This PR was made for the v0 so actually ill close this ticket for now

**Pull request closed without merging**
